/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include <time.h>
#include <stdlib.h>
 #include <string.h>

char **
add_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	time_t t = time(NULL);
	struct tm tm = *localtime(&t);

	printf("%s", *argp);
	printf("%s", asctime(localtime(&t)));
	
FILE *f = fopen("file.txt", "a+");
if (f == NULL)
{
    printf("Error opening file!\n");
    exit(1);
}

/* print some text */

	

fprintf(f,"%s",  *argp );
fprintf(f," ");
fprintf(f,"%s", (asctime(localtime(&t))  )  );
fclose(f);


	return &result;
}

char **
search_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;
	int count;
	printf("LLegamos metodo 2\n");
	
	FILE *f = fopen("file.txt", "a+");
	if (f == NULL)
	{
    	printf("Error opening file!\n");
   	 exit(1);
	}


	char *s;

	const size_t line_size = 300;
	char* line = malloc(line_size);
	while (fgets(line, line_size, f) != NULL)
	{
    	s = strstr(line, *argp);
		if (s != NULL)
		{
			count++;
		}

	printf("Se contaron %d %s \n" , count, *argp);

if (fgets(line, line_size, f) == NULL){
fclose(f);}
	
	}



	
	printf("Salimso while");

	asprintf(&result, "Se contaron", *argp, count, "este fue el resultado final");

       

	return &result;
}
