/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"


void
add_prog_1(char *host , int num, char *name)
{
	CLIENT *clnt;
	char * *result_1;
	char * add_1_arg;
	char * *result_2;
	char * search_1_arg;




#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

if(num == 1)
{
	printf("Metodo 1");
}
else
{

printf("Metodo 2");

	add_1_arg = name;
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		//clnt_perror (clnt, "call failed");
	}
	search_1_arg = name;
	result_2 = search_1(&search_1_arg, clnt);
	if (result_2 == (char **) NULL) {
		//clnt_perror (clnt, "call failed");
	}


}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *name;
	int a;


	if (argc != 4) {
		printf ("usage: %s server_host num1\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	a = atoi(argv[2]);
	name = argv[3];
	


	

	add_prog_1 (host , a, name);
exit (0);
}
