/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "suma.h"
#include <time.h>

int *
suma_1_svc(char **argp, struct svc_req *rqstp)
{
	static string  result;

	/*
	 * insert server code here
	 */
	//printf("Server response to client...\n");
	printf("Server is working \n");


	time_t t = time(NULL);
	struct tm tm = *localtime(&t);

	printf("Server response: %s: %d-%d-%d %d:%d:%d\n", *argp, tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday, tm.tm_hour, tm.tm_min, tm.tm_sec)

	return &result;
}
